# Generated by Django 4.2.4 on 2023-08-08 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='long_description',
            field=models.CharField(default='ehllo this ', max_length=500),
            preserve_default=False,
        ),
    ]
